import { playBeep } from "@/utils/beep";
import { Ionicons } from "@expo/vector-icons";
import React, { useState } from "react";
import {
  Alert,
  ScrollView,
  Switch,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";

interface AddWorkerProps {
  onBack?: () => void;
}

export default function AddWorker({ onBack }: AddWorkerProps) {
  const [form, setForm] = useState({
    name: "",
    email: "",
    phoneNumber: "", // Added phone number
    salary: "",
    role: "worker",
    faceidEnabled: false,
  });

  const handleSave = async () => {
    // Validation: Admin must provide these fields
    if (!form.name || !form.email || !form.phoneNumber) {
      Alert.alert(
        "Missing Info",
        "Please provide Name, Email, and Phone Number.",
      );
      return;
    }

    await playBeep();
    
    // Logic: Send only admin-defined fields to backend
    // Backend will handle generation of PIN, Password, and Worker Email
    console.log("Sending to Backend:", form);
    
    Alert.alert(
      "Success", 
      `${form.name} registered. System is generating credentials...`
    );
  };

  return (
    <ScrollView className="flex-1 bg-white">
      {/* Header */}
      <View className="px-6 pt-12 pb-6 border-b border-slate-50 bg-slate-50/50 flex-row justify-between items-end">
        <View className="flex-1">
          <Text className="text-2xl font-bold text-slate-900">New Employee</Text>
          <Text className="text-slate-500 text-sm">
            Credentials will be auto-generated by the system.
          </Text>
        </View>

        {onBack && (
          <TouchableOpacity
            onPress={onBack}
            className="flex-row items-center bg-slate-100 px-3 py-2 rounded-lg"
          >
            <Ionicons name="arrow-back" size={20} color="#475569" />
            <Text className="text-slate-600 font-bold ml-1">Back</Text>
          </TouchableOpacity>
        )}
      </View>

      <View className="p-6">
        <Text className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-6">
          Required Information
        </Text>

        {/* Name & Username Row */}
        <View className="flex-row mb-5">
          <View className="flex-1 mr-3">
            <Text className="text-xs font-semibold text-slate-700 mb-2">Full Name</Text>
            <TextInput
              className="border-b border-slate-200 py-2 text-base text-slate-900"
              placeholder="John Doe"
              onChangeText={(val) => setForm({ ...form, name: val })}
            />
          </View>

        </View>

        {/* Email & Phone Row */}
        <View className="flex-row mb-5">
          <View className="flex-1 mr-3">
            <Text className="text-xs font-semibold text-slate-700 mb-2">Personal Email</Text>
            <TextInput
              className="border-b border-slate-200 py-2 text-base text-slate-900"
              keyboardType="email-address"
              placeholder="john@me.com"
              autoCapitalize="none"
              onChangeText={(val) => setForm({ ...form, email: val })}
            />
          </View>
          <View className="flex-1">
            <Text className="text-xs font-semibold text-slate-700 mb-2">Phone Number</Text>
            <TextInput
              className="border-b border-slate-200 py-2 text-base text-slate-900"
              keyboardType="phone-pad"
              placeholder="+250..."
              onChangeText={(val) => setForm({ ...form, phoneNumber: val })}
            />
          </View>
        </View>

        {/* Salary */}
        <View className="mb-8">
          <Text className="text-xs font-semibold text-slate-700 mb-2">Monthly Salary (RWF)</Text>
          <TextInput
            className="bg-slate-50 p-4 rounded-xl border border-slate-100 font-bold text-lg text-emerald-700"
            keyboardType="numeric"
            placeholder="50,000"
            onChangeText={(val) => setForm({ ...form, salary: val })}
          />
        </View>

        {/* Role Selection */}
        <Text className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-4">
          Assign Role
        </Text>
        <View className="flex-row mb-8">
          {["worker", "owner"].map((role) => (
            <TouchableOpacity
              key={role}
              onPress={() => setForm({ ...form, role: role as any })}
              className={`flex-1 p-4 rounded-xl border-2 mr-2 items-center ${
                form.role === role ? "border-slate-900 bg-slate-900" : "border-slate-100 bg-white"
              }`}
            >
              <Ionicons
                name={role === "owner" ? "shield-checkmark" : "person"}
                size={22}
                color={form.role === role ? "white" : "#94a3b8"}
              />
              <Text className={`mt-2 font-bold capitalize ${form.role === role ? "text-white" : "text-slate-400"}`}>
                {role}
              </Text>
            </TouchableOpacity>
          ))}
        </View>

        {/* Biometrics */}
        <View className="flex-row justify-between items-center bg-slate-50 p-4 rounded-2xl mb-10">
          <View>
            <Text className="font-bold text-slate-900">Enable Biometrics</Text>
            <Text className="text-xs text-slate-500">Allow FaceID for faster clock-in</Text>
          </View>
          <Switch
            value={form.faceidEnabled}
            onValueChange={(val) => setForm({ ...form, faceidEnabled: val })}
            trackColor={{ false: "#cbd5e1", true: "#0f172a" }}
          />
        </View>

        {/* Submit */}
        <TouchableOpacity
          onPress={handleSave}
          activeOpacity={0.8}
          className="bg-slate-900 p-5 rounded-2xl flex-row justify-center items-center shadow-xl shadow-slate-300"
        >
          <Ionicons name="cloud-upload" size={22} color="white" />
          <Text className="text-white font-bold text-lg ml-2">Register & Generate</Text>
        </TouchableOpacity>
      </View>
    </ScrollView>
  );
}