import { playBeep } from "@/utils/beep";
import { Ionicons } from "@expo/vector-icons";
import React, { useEffect, useState } from "react";
import { Picker } from "@react-native-picker/picker";
import useRole from "@/store/Employee/useRole";
import useEmployee from "@/store/Employee/UseEmploye";
import Toast from "react-native-toast-message";
import ProductImagePicker from "@/app/components/ownerComponents/ProductImagePicker";
import {
  Alert,
  ScrollView,
  Switch,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";

interface AddWorkerProps {
  onBack?: () => void;
}

export type ShiftType = "DAY" | "EVENING" | "NIGHT" | "HYBRID";
export default function AddWorker({ onBack }: AddWorkerProps) {
  const [form, setForm] = useState({
    profile: "",
    name: "",
    email: "",
    phoneNumber: "",
    salary: "",
    role: "",
    shift: "" as ShiftType | "",
  });
  const { addEmployee } = useEmployee();
  const { rolesResponse, getRoles } = useRole();
  useEffect(() => {
    const fetchRoles = async () => {
      await getRoles();
    };
    fetchRoles();
  }, []);

  const handleSave = async () => {
    if (!form.name || !form.email || !form.phoneNumber) {
      Alert.alert(
        "Missing Info",
        "Please provide Name, Email, and Phone Number.",
      );
      return;
    }
    try {
      await addEmployee({
        profile: form.profile,
        name: form.name.trim(),
        email: form.email.trim(),
        phone: form.phoneNumber.trim(),
        salary: Number(form.salary) || 0,
        shift: form.shift, // now safe
        roleId: form.role,
      });

      await playBeep();

      Toast.show({
        type: "success",
        text1: "Success",
        text2: `${form.name} registered. System is generating credentials...`,
      });

      console.log("Sending to Backend:", form);
    } catch (error: any) {
      console.error("Add Employee Error:", error);

      Toast.show({
        type: "error",
        text1: "Failed",
        text2: error.message || "Something went wrong",
      });
    } finally {
    }
  };

  return (
    <ScrollView className="flex-1 bg-white">
      {/* Header */}
      <View className="px-6  pb-6 border-b border-slate-50 bg-slate-50/50 flex-row justify-between items-end">
        <View className="flex-1">
          <Text className="text-2xl font-bold text-green-600">
            New Employee
          </Text>
          <Text className="text-slate-500 text-sm">
            Credentials will be auto-generated by the system.
          </Text>
        </View>

        {onBack && (
          <TouchableOpacity
            onPress={onBack}
            className="flex-row items-center px-4 py-2 bg-green-600 rounded-lg"
          >
            <Ionicons name="arrow-back" size={20} color="white" />
            <Text className="text-white font-bold ml-1">View Employees</Text>
          </TouchableOpacity>
        )}
      </View>

      <View className="p-6">
        <Text className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-6">
          Required Information
        </Text>
        <ProductImagePicker name="Profile Image" />

        {/* Name & Username Row */}
        <View className="flex-row mb-5">
          <View className="flex-1 mr-3">
            <Text className="text-xs font-semibold text-slate-700 mb-2">
              Full Name
            </Text>
            <TextInput
              className="border-b border-slate-200 outline-none py-2 text-base text-slate-900"
              placeholder="John Doe"
              onChangeText={(val) => setForm({ ...form, name: val })}
            />
          </View>
        </View>

        {/* Email & Phone Row */}
        <View className="flex-row mb-5">
          <View className="flex-1 mr-3">
            <Text className="text-xs font-semibold text-slate-700 mb-2">
              Personal Email
            </Text>
            <TextInput
              className="border-b border-slate-200 outline-none py-2 text-base text-slate-900"
              keyboardType="email-address"
              placeholder="john@me.com"
              autoCapitalize="none"
              onChangeText={(val) => setForm({ ...form, email: val })}
            />
          </View>
          <View className="flex-1">
            <Text className="text-xs font-semibold text-slate-700 mb-2">
              Phone Number
            </Text>
            <TextInput
              className="border-b outline-none border-slate-200 py-2 text-base text-slate-900"
              keyboardType="phone-pad"
              placeholder="+250..."
              onChangeText={(val) => setForm({ ...form, phoneNumber: val })}
            />
          </View>
        </View>

        <View className="flex-row mb-5">
          <View className="flex-1 mr-3 hidden">
            <Text className="text-xs font-semibold text-slate-700 mb-2">
              Payment Date
            </Text>
            <TextInput
              className="border-b border-slate-200 outline-none py-2 text-base text-slate-900"
              keyboardType="number-pad"
              placeholder="e.g. 25th of every month"
              autoCapitalize="none"
              onChangeText={(val) => setForm({ ...form, email: val })}
            />
          </View>
          <View className="flex-1 mr-3 ">
            <Text className="text-xs font-semibold text-slate-700 mb-2">
              Shift
            </Text>
            <Picker
              selectedValue={form.shift}
              onValueChange={(itemValue) =>
                setForm({ ...form, shift: itemValue })
              }
              className="border-b border-slate-200 outline-none py-2 text-base text-slate-900"
            >
              <Picker.Item key="" label="Select Shift" value="" />
              <Picker.Item key="DAY" label="Morning Shift" value="DAY" />
              <Picker.Item
                key="EVENING"
                label="Afternoon Shift"
                value="EVENING"
              />
              <Picker.Item key="NIGHT" label="Night Shift" value="NIGHT" />
              <Picker.Item key="HYBRID" label="Hybrid Shift" value="HYBRID" />
            </Picker>
          </View>
          <View className="flex-1">
            <Text className="text-xs font-semibold text-slate-700 mb-2">
              Monthly Salary (RWF)
            </Text>
            <TextInput
              className="border-b outline-none border-slate-200 py-2 text-base text-slate-900"
              keyboardType="phone-pad"
              placeholder="100,000 RWF"
              onChangeText={(val) => setForm({ ...form, salary: val })}
            />
          </View>
        </View>

        {/* Role Selection */}
        <Text className="text-[10px] font-bold  uppercase tracking-widest mb-4">
          Assign Role
        </Text>
        <Picker
          selectedValue={form.role}
          onValueChange={(itemValue) => setForm({ ...form, role: itemValue })}
          className="mb-5 border border-gray-200 outline-none rounded-lg py-3"
        >
          <Picker.Item key="" label="All roles" value="" />
          {rolesResponse.map((role) => (
            <Picker.Item key={role.id} label={role.name} value={role.id} />
          ))}
        </Picker>

        {/* Submit */}
        <TouchableOpacity
          onPress={handleSave}
          activeOpacity={0.8}
          className="bg-green-900 p-5 rounded-2xl flex-row justify-center items-center shadow-xl shadow-slate-300"
        >
          <Ionicons name="cloud-upload" size={22} color="white" />
          <Text className="text-white font-bold text-lg ml-2">
            Register & Generate
          </Text>
        </TouchableOpacity>
      </View>
    </ScrollView>
  );
}
