import ProductImagePicker from "@/app/components/ownerComponents/ProductImagePicker";
import useEmployee from "@/store/Employee/UseEmploye";
import useRole from "@/store/Employee/useRole";
import { playBeep } from "@/utils/beep";
import { Ionicons } from "@expo/vector-icons";
import { Picker } from "@react-native-picker/picker";
import React, { useEffect, useState } from "react";
import {
  Alert,
  Image,
  Modal,
  Platform,
  ScrollView,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";
import Toast from "react-native-toast-message";

interface AddWorkerProps {
  onBack?: () => void;
}

export type ShiftType = "DAY" | "EVENING" | "NIGHT" | "HYBRID";
interface RegistrationDetails {
  name: string;
  email: string;
  profile: string;
  pin: string;
  password: string;
}

export default function AddWorker({ onBack }: AddWorkerProps) {
  const [form, setForm] = useState({
    profile: "",
    profileFile: null as Blob | null,
    name: "",
    email: "",
    phoneNumber: "",
    salary: "",
    role: "",
    shift: "" as ShiftType | "",
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [registrationDetails, setRegistrationDetails] =
    useState<RegistrationDetails | null>(null);
  const { addEmployee } = useEmployee();
  const { rolesResponse, getRoles } = useRole();
  useEffect(() => {
    const fetchRoles = async () => {
      await getRoles();
    };
    fetchRoles();
  }, []);

  const handleSave = async () => {
    if (!form.name || !form.email || !form.phoneNumber) {
      Alert.alert(
        "Missing Info",
        "Please provide Name, Email, and Phone Number.",
      );
      return;
    }
    if (!form.profile) {
      Alert.alert("Missing Image", "Please select a profile image.");
      return;
    }
    try {
      setIsSubmitting(true);
      const formData = new FormData();
      formData.append("name", form.name.trim());
      formData.append("email", form.email.trim());
      formData.append("phone", form.phoneNumber.trim());
      formData.append("salary", String(Number(form.salary) || 0));
      formData.append("shift", form.shift || "DAY");
      formData.append("roleId", form.role);
      if (Platform.OS === "web") {
        let picture: Blob;
        if (form.profileFile) {
          picture = form.profileFile;
        } else {
          picture = await fetch(form.profile).then((response) =>
            response.blob(),
          );
        }
        formData.append("picture", picture, "employee.jpg");
      } else {
        formData.append("picture", {
          uri: form.profile,
          name: "employee.jpg",
          type: "image/jpeg",
        } as any);
      }

      const response = await addEmployee(formData);
      const responseData = response.data as Record<string, unknown> | undefined;
      const responseCredentials = response.credentials as
        | Record<string, unknown>
        | undefined;
      const dataCredentials = responseData?.credentials as
        | Record<string, unknown>
        | undefined;
      const getResponseValue = (keys: string[]) => {
        for (const key of keys) {
          const value =
            response[key] ??
            responseData?.[key] ??
            responseCredentials?.[key] ??
            dataCredentials?.[key];
          if (value !== undefined && value !== null) return String(value);
        }
        return "Not provided";
      };

      setRegistrationDetails({
        name: form.name.trim(),
        email: form.email.trim(),
        profile: form.profile,
        pin: getResponseValue(["pin", "pinCode", "generatedPin"]),
        password: getResponseValue([
          "password",
          "temporaryPassword",
          "generatedPassword",
        ]),
      });

      await playBeep();

      Toast.show({
        type: "success",
        text1: "Success",
        text2: `${form.name} registered. System is generating credentials...`,
      });

      console.log("Sending to Backend:", form);
    } catch (error: any) {
      console.error("Add Employee Error:", error);

      Toast.show({
        type: "error",
        text1: "Failed",
        text2: error.message || "Something went wrong",
      });
      Alert.alert(
        "Registration Failed",
        error.message || "Something went wrong",
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <ScrollView className="flex-1 bg-white">
      {/* Header */}
      <View className="px-6  pb-6 border-b border-slate-50 bg-slate-50/50 flex-row justify-between items-end">
        <View className="flex-1">
          <Text className="text-2xl font-bold text-green-600">
            New Employee
          </Text>
          <Text className="text-slate-500 text-sm">
            Credentials will be auto-generated by the system.
          </Text>
        </View>

        {onBack && (
          <TouchableOpacity
            onPress={onBack}
            className="flex-row items-center px-4 py-2 bg-green-600 rounded-lg"
          >
            <Ionicons name="arrow-back" size={20} color="white" />
            <Text className="text-white font-bold ml-1">View Employees</Text>
          </TouchableOpacity>
        )}
      </View>

      <View className="p-6">
        <Text className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-6">
          Required Information
        </Text>
        <ProductImagePicker
          name="Profile Image"
          onImageSelected={(uri, file) =>
            setForm({ ...form, profile: uri ?? "", profileFile: file ?? null })
          }
        />

        {/* Name & Username Row */}
        <View className="flex-row mb-5">
          <View className="flex-1 mr-3">
            <Text className="text-xs font-semibold text-slate-700 mb-2">
              Full Name
            </Text>
            <TextInput
              className="border-b border-slate-200 outline-none py-2 text-base text-slate-900"
              placeholder="John Doe"
              onChangeText={(val) => setForm({ ...form, name: val })}
            />
          </View>
        </View>

        {/* Email & Phone Row */}
        <View className="flex-row mb-5">
          <View className="flex-1 mr-3">
            <Text className="text-xs font-semibold text-slate-700 mb-2">
              Personal Email
            </Text>
            <TextInput
              className="border-b border-slate-200 outline-none py-2 text-base text-slate-900"
              keyboardType="email-address"
              placeholder="john@me.com"
              autoCapitalize="none"
              onChangeText={(val) => setForm({ ...form, email: val })}
            />
          </View>
          <View className="flex-1">
            <Text className="text-xs font-semibold text-slate-700 mb-2">
              Phone Number
            </Text>
            <TextInput
              className="border-b outline-none border-slate-200 py-2 text-base text-slate-900"
              keyboardType="phone-pad"
              placeholder="+250..."
              onChangeText={(val) => setForm({ ...form, phoneNumber: val })}
            />
          </View>
        </View>

        <View className="flex-row mb-5">
          <View className="flex-1 mr-3 hidden">
            <Text className="text-xs font-semibold text-slate-700 mb-2">
              Payment Date
            </Text>
            <TextInput
              className="border-b border-slate-200 outline-none py-2 text-base text-slate-900"
              keyboardType="number-pad"
              placeholder="e.g. 25th of every month"
              autoCapitalize="none"
              onChangeText={(val) => setForm({ ...form, email: val })}
            />
          </View>
          <View className="flex-1 mr-3 ">
            <Text className="text-xs font-semibold text-slate-700 mb-2">
              Shift
            </Text>
            <Picker
              selectedValue={form.shift}
              onValueChange={(itemValue) =>
                setForm({ ...form, shift: itemValue })
              }
              className="border-b border-slate-200 outline-none py-2 text-base text-slate-900"
            >
              <Picker.Item key="" label="Select Shift" value="" />
              <Picker.Item key="DAY" label="Morning Shift" value="DAY" />
              <Picker.Item
                key="EVENING"
                label="Afternoon Shift"
                value="EVENING"
              />
              <Picker.Item key="NIGHT" label="Night Shift" value="NIGHT" />
              <Picker.Item key="HYBRID" label="Hybrid Shift" value="HYBRID" />
            </Picker>
          </View>
          <View className="flex-1">
            <Text className="text-xs font-semibold text-slate-700 mb-2">
              Monthly Salary (RWF)
            </Text>
            <TextInput
              className="border-b outline-none border-slate-200 py-2 text-base text-slate-900"
              keyboardType="phone-pad"
              placeholder="100,000 RWF"
              onChangeText={(val) => setForm({ ...form, salary: val })}
            />
          </View>
        </View>

        {/* Role Selection */}
        <Text className="text-[10px] font-bold  uppercase tracking-widest mb-4">
          Assign Role
        </Text>
        <Picker
          selectedValue={form.role}
          onValueChange={(itemValue) => setForm({ ...form, role: itemValue })}
          className="mb-5 border border-gray-200 outline-none rounded-lg py-3"
        >
          <Picker.Item key="" label="All roles" value="" />
          {rolesResponse.map((role) => (
            <Picker.Item key={role.id} label={role.name} value={role.id} />
          ))}
        </Picker>

        {/* Submit */}
        <TouchableOpacity
          onPress={handleSave}
          disabled={isSubmitting}
          activeOpacity={0.8}
          className={`bg-green-900 p-5 rounded-2xl flex-row justify-center items-center shadow-xl shadow-slate-300 ${isSubmitting ? "opacity-60" : ""}`}
        >
          <Ionicons name="cloud-upload" size={22} color="white" />
          <Text className="text-white font-bold text-lg ml-2">
            {isSubmitting ? "Registering..." : "Register & Generate"}
          </Text>
        </TouchableOpacity>
      </View>

      <Modal
        visible={registrationDetails !== null}
        transparent
        animationType="fade"
        onRequestClose={() => setRegistrationDetails(null)}
      >
        <View className="flex-1 bg-black/50 justify-center items-center px-6">
          <View className="w-full max-w-md bg-white rounded-2xl p-6">
            <Text className="text-2xl font-bold text-green-700 text-center">
              Employee Registered
            </Text>
            <Text className="text-slate-500 text-center mt-1 mb-5">
              Save these login credentials securely.
            </Text>

            {registrationDetails?.profile ? (
              <Image
                source={{ uri: registrationDetails.profile }}
                className="w-24 h-24 rounded-full self-center mb-4"
              />
            ) : null}

            <View className="bg-slate-50 rounded-xl p-4 gap-3">
              <Text className="text-slate-800">
                <Text className="font-bold">Name: </Text>
                {registrationDetails?.name}
              </Text>
              <Text className="text-slate-800">
                <Text className="font-bold">Email: </Text>
                {registrationDetails?.email}
              </Text>
              <Text className="text-slate-800">
                <Text className="font-bold">PIN: </Text>
                {registrationDetails?.pin}
              </Text>
              <Text className="text-slate-800">
                <Text className="font-bold">Password: </Text>
                {registrationDetails?.password}
              </Text>
            </View>

            <TouchableOpacity
              onPress={() => setRegistrationDetails(null)}
              className="bg-green-700 rounded-xl p-4 mt-5"
            >
              <Text className="text-white font-bold text-center">Done</Text>
            </TouchableOpacity>
          </View>
        </View>
      </Modal>
    </ScrollView>
  );
}
