name: EAS Android Build
on:
  push:
    branches:
      - main # Change this to 'master' if your default branch is named master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Updated to Node 24 to match GitHub's environment smoothly

      - name: ⚙️ Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm # 👈 This forces Expo to use NPM instead of Yarn

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🚀 Trigger EAS Build
        run: eas build --platform android --profile development --non-interactive
